# Generated by Django 3.0 on 2020-01-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openweather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercity',
            name='nospace_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
