# Generated by Django 3.0 on 2020-01-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openweather', '0002_weathercity_nospace_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercity',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
