# Generated by Django 3.0 on 2020-01-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openweather', '0003_weathercity_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercity',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
    ]
